// Mocks generated by Mockito 5.4.6 from annotations
// in telissy/test/client_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:t/t.dart' as _i3;
import 'package:tg/tg.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthorizationKey_0 extends _i1.SmartFake
    implements _i2.AuthorizationKey {
  _FakeAuthorizationKey_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeObfuscation_1 extends _i1.SmartFake implements _i2.Obfuscation {
  _FakeObfuscation_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSocketAbstraction_2 extends _i1.SmartFake
    implements _i2.SocketAbstraction {
  _FakeSocketAbstraction_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessageIdGenerator_3 extends _i1.SmartFake
    implements _i2.MessageIdGenerator {
  _FakeMessageIdGenerator_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientAuth_4 extends _i1.SmartFake implements _i3.ClientAuth {
  _FakeClientAuth_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientAccount_5 extends _i1.SmartFake implements _i3.ClientAccount {
  _FakeClientAccount_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientUsers_6 extends _i1.SmartFake implements _i3.ClientUsers {
  _FakeClientUsers_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientContacts_7 extends _i1.SmartFake
    implements _i3.ClientContacts {
  _FakeClientContacts_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientMessages_8 extends _i1.SmartFake
    implements _i3.ClientMessages {
  _FakeClientMessages_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientUpdates_9 extends _i1.SmartFake implements _i3.ClientUpdates {
  _FakeClientUpdates_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientPhotos_10 extends _i1.SmartFake implements _i3.ClientPhotos {
  _FakeClientPhotos_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientUpload_11 extends _i1.SmartFake implements _i3.ClientUpload {
  _FakeClientUpload_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientHelp_12 extends _i1.SmartFake implements _i3.ClientHelp {
  _FakeClientHelp_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientChannels_13 extends _i1.SmartFake
    implements _i3.ClientChannels {
  _FakeClientChannels_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientBots_14 extends _i1.SmartFake implements _i3.ClientBots {
  _FakeClientBots_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientPayments_15 extends _i1.SmartFake
    implements _i3.ClientPayments {
  _FakeClientPayments_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientStickers_16 extends _i1.SmartFake
    implements _i3.ClientStickers {
  _FakeClientStickers_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientPhone_17 extends _i1.SmartFake implements _i3.ClientPhone {
  _FakeClientPhone_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientLangpack_18 extends _i1.SmartFake
    implements _i3.ClientLangpack {
  _FakeClientLangpack_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientFolders_19 extends _i1.SmartFake implements _i3.ClientFolders {
  _FakeClientFolders_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientStats_20 extends _i1.SmartFake implements _i3.ClientStats {
  _FakeClientStats_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientChatlists_21 extends _i1.SmartFake
    implements _i3.ClientChatlists {
  _FakeClientChatlists_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientStories_22 extends _i1.SmartFake implements _i3.ClientStories {
  _FakeClientStories_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientPremium_23 extends _i1.SmartFake implements _i3.ClientPremium {
  _FakeClientPremium_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientSmsjobs_24 extends _i1.SmartFake implements _i3.ClientSmsjobs {
  _FakeClientSmsjobs_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientFragment_25 extends _i1.SmartFake
    implements _i3.ClientFragment {
  _FakeClientFragment_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientAicompose_26 extends _i1.SmartFake
    implements _i3.ClientAicompose {
  _FakeClientAicompose_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResult_27<T extends _i3.TlObject> extends _i1.SmartFake
    implements _i3.Result<T> {
  _FakeResult_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i2.Client {
  @override
  _i2.AuthorizationKey get authorizationKey =>
      (super.noSuchMethod(
            Invocation.getter(#authorizationKey),
            returnValue: _FakeAuthorizationKey_0(
              this,
              Invocation.getter(#authorizationKey),
            ),
            returnValueForMissingStub: _FakeAuthorizationKey_0(
              this,
              Invocation.getter(#authorizationKey),
            ),
          )
          as _i2.AuthorizationKey);

  @override
  _i2.Obfuscation get obfuscation =>
      (super.noSuchMethod(
            Invocation.getter(#obfuscation),
            returnValue: _FakeObfuscation_1(
              this,
              Invocation.getter(#obfuscation),
            ),
            returnValueForMissingStub: _FakeObfuscation_1(
              this,
              Invocation.getter(#obfuscation),
            ),
          )
          as _i2.Obfuscation);

  @override
  _i2.SocketAbstraction get socket =>
      (super.noSuchMethod(
            Invocation.getter(#socket),
            returnValue: _FakeSocketAbstraction_2(
              this,
              Invocation.getter(#socket),
            ),
            returnValueForMissingStub: _FakeSocketAbstraction_2(
              this,
              Invocation.getter(#socket),
            ),
          )
          as _i2.SocketAbstraction);

  @override
  _i2.MessageIdGenerator get idGenerator =>
      (super.noSuchMethod(
            Invocation.getter(#idGenerator),
            returnValue: _FakeMessageIdGenerator_3(
              this,
              Invocation.getter(#idGenerator),
            ),
            returnValueForMissingStub: _FakeMessageIdGenerator_3(
              this,
              Invocation.getter(#idGenerator),
            ),
          )
          as _i2.MessageIdGenerator);

  @override
  Set<int> get msgsToAck =>
      (super.noSuchMethod(
            Invocation.getter(#msgsToAck),
            returnValue: <int>{},
            returnValueForMissingStub: <int>{},
          )
          as Set<int>);

  @override
  _i4.Stream<_i3.UpdatesBase> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i4.Stream<_i3.UpdatesBase>.empty(),
            returnValueForMissingStub: _i4.Stream<_i3.UpdatesBase>.empty(),
          )
          as _i4.Stream<_i3.UpdatesBase>);

  @override
  set authorizationKey(_i2.AuthorizationKey? value) => super.noSuchMethod(
    Invocation.setter(#authorizationKey, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.ClientAuth get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeClientAuth_4(this, Invocation.getter(#auth)),
            returnValueForMissingStub: _FakeClientAuth_4(
              this,
              Invocation.getter(#auth),
            ),
          )
          as _i3.ClientAuth);

  @override
  _i3.ClientAccount get account =>
      (super.noSuchMethod(
            Invocation.getter(#account),
            returnValue: _FakeClientAccount_5(
              this,
              Invocation.getter(#account),
            ),
            returnValueForMissingStub: _FakeClientAccount_5(
              this,
              Invocation.getter(#account),
            ),
          )
          as _i3.ClientAccount);

  @override
  _i3.ClientUsers get users =>
      (super.noSuchMethod(
            Invocation.getter(#users),
            returnValue: _FakeClientUsers_6(this, Invocation.getter(#users)),
            returnValueForMissingStub: _FakeClientUsers_6(
              this,
              Invocation.getter(#users),
            ),
          )
          as _i3.ClientUsers);

  @override
  _i3.ClientContacts get contacts =>
      (super.noSuchMethod(
            Invocation.getter(#contacts),
            returnValue: _FakeClientContacts_7(
              this,
              Invocation.getter(#contacts),
            ),
            returnValueForMissingStub: _FakeClientContacts_7(
              this,
              Invocation.getter(#contacts),
            ),
          )
          as _i3.ClientContacts);

  @override
  _i3.ClientMessages get messages =>
      (super.noSuchMethod(
            Invocation.getter(#messages),
            returnValue: _FakeClientMessages_8(
              this,
              Invocation.getter(#messages),
            ),
            returnValueForMissingStub: _FakeClientMessages_8(
              this,
              Invocation.getter(#messages),
            ),
          )
          as _i3.ClientMessages);

  @override
  _i3.ClientUpdates get updates =>
      (super.noSuchMethod(
            Invocation.getter(#updates),
            returnValue: _FakeClientUpdates_9(
              this,
              Invocation.getter(#updates),
            ),
            returnValueForMissingStub: _FakeClientUpdates_9(
              this,
              Invocation.getter(#updates),
            ),
          )
          as _i3.ClientUpdates);

  @override
  _i3.ClientPhotos get photos =>
      (super.noSuchMethod(
            Invocation.getter(#photos),
            returnValue: _FakeClientPhotos_10(this, Invocation.getter(#photos)),
            returnValueForMissingStub: _FakeClientPhotos_10(
              this,
              Invocation.getter(#photos),
            ),
          )
          as _i3.ClientPhotos);

  @override
  _i3.ClientUpload get upload =>
      (super.noSuchMethod(
            Invocation.getter(#upload),
            returnValue: _FakeClientUpload_11(this, Invocation.getter(#upload)),
            returnValueForMissingStub: _FakeClientUpload_11(
              this,
              Invocation.getter(#upload),
            ),
          )
          as _i3.ClientUpload);

  @override
  _i3.ClientHelp get help =>
      (super.noSuchMethod(
            Invocation.getter(#help),
            returnValue: _FakeClientHelp_12(this, Invocation.getter(#help)),
            returnValueForMissingStub: _FakeClientHelp_12(
              this,
              Invocation.getter(#help),
            ),
          )
          as _i3.ClientHelp);

  @override
  _i3.ClientChannels get channels =>
      (super.noSuchMethod(
            Invocation.getter(#channels),
            returnValue: _FakeClientChannels_13(
              this,
              Invocation.getter(#channels),
            ),
            returnValueForMissingStub: _FakeClientChannels_13(
              this,
              Invocation.getter(#channels),
            ),
          )
          as _i3.ClientChannels);

  @override
  _i3.ClientBots get bots =>
      (super.noSuchMethod(
            Invocation.getter(#bots),
            returnValue: _FakeClientBots_14(this, Invocation.getter(#bots)),
            returnValueForMissingStub: _FakeClientBots_14(
              this,
              Invocation.getter(#bots),
            ),
          )
          as _i3.ClientBots);

  @override
  _i3.ClientPayments get payments =>
      (super.noSuchMethod(
            Invocation.getter(#payments),
            returnValue: _FakeClientPayments_15(
              this,
              Invocation.getter(#payments),
            ),
            returnValueForMissingStub: _FakeClientPayments_15(
              this,
              Invocation.getter(#payments),
            ),
          )
          as _i3.ClientPayments);

  @override
  _i3.ClientStickers get stickers =>
      (super.noSuchMethod(
            Invocation.getter(#stickers),
            returnValue: _FakeClientStickers_16(
              this,
              Invocation.getter(#stickers),
            ),
            returnValueForMissingStub: _FakeClientStickers_16(
              this,
              Invocation.getter(#stickers),
            ),
          )
          as _i3.ClientStickers);

  @override
  _i3.ClientPhone get phone =>
      (super.noSuchMethod(
            Invocation.getter(#phone),
            returnValue: _FakeClientPhone_17(this, Invocation.getter(#phone)),
            returnValueForMissingStub: _FakeClientPhone_17(
              this,
              Invocation.getter(#phone),
            ),
          )
          as _i3.ClientPhone);

  @override
  _i3.ClientLangpack get langpack =>
      (super.noSuchMethod(
            Invocation.getter(#langpack),
            returnValue: _FakeClientLangpack_18(
              this,
              Invocation.getter(#langpack),
            ),
            returnValueForMissingStub: _FakeClientLangpack_18(
              this,
              Invocation.getter(#langpack),
            ),
          )
          as _i3.ClientLangpack);

  @override
  _i3.ClientFolders get folders =>
      (super.noSuchMethod(
            Invocation.getter(#folders),
            returnValue: _FakeClientFolders_19(
              this,
              Invocation.getter(#folders),
            ),
            returnValueForMissingStub: _FakeClientFolders_19(
              this,
              Invocation.getter(#folders),
            ),
          )
          as _i3.ClientFolders);

  @override
  _i3.ClientStats get stats =>
      (super.noSuchMethod(
            Invocation.getter(#stats),
            returnValue: _FakeClientStats_20(this, Invocation.getter(#stats)),
            returnValueForMissingStub: _FakeClientStats_20(
              this,
              Invocation.getter(#stats),
            ),
          )
          as _i3.ClientStats);

  @override
  _i3.ClientChatlists get chatlists =>
      (super.noSuchMethod(
            Invocation.getter(#chatlists),
            returnValue: _FakeClientChatlists_21(
              this,
              Invocation.getter(#chatlists),
            ),
            returnValueForMissingStub: _FakeClientChatlists_21(
              this,
              Invocation.getter(#chatlists),
            ),
          )
          as _i3.ClientChatlists);

  @override
  _i3.ClientStories get stories =>
      (super.noSuchMethod(
            Invocation.getter(#stories),
            returnValue: _FakeClientStories_22(
              this,
              Invocation.getter(#stories),
            ),
            returnValueForMissingStub: _FakeClientStories_22(
              this,
              Invocation.getter(#stories),
            ),
          )
          as _i3.ClientStories);

  @override
  _i3.ClientPremium get premium =>
      (super.noSuchMethod(
            Invocation.getter(#premium),
            returnValue: _FakeClientPremium_23(
              this,
              Invocation.getter(#premium),
            ),
            returnValueForMissingStub: _FakeClientPremium_23(
              this,
              Invocation.getter(#premium),
            ),
          )
          as _i3.ClientPremium);

  @override
  _i3.ClientSmsjobs get smsjobs =>
      (super.noSuchMethod(
            Invocation.getter(#smsjobs),
            returnValue: _FakeClientSmsjobs_24(
              this,
              Invocation.getter(#smsjobs),
            ),
            returnValueForMissingStub: _FakeClientSmsjobs_24(
              this,
              Invocation.getter(#smsjobs),
            ),
          )
          as _i3.ClientSmsjobs);

  @override
  _i3.ClientFragment get fragment =>
      (super.noSuchMethod(
            Invocation.getter(#fragment),
            returnValue: _FakeClientFragment_25(
              this,
              Invocation.getter(#fragment),
            ),
            returnValueForMissingStub: _FakeClientFragment_25(
              this,
              Invocation.getter(#fragment),
            ),
          )
          as _i3.ClientFragment);

  @override
  _i3.ClientAicompose get aicompose =>
      (super.noSuchMethod(
            Invocation.getter(#aicompose),
            returnValue: _FakeClientAicompose_26(
              this,
              Invocation.getter(#aicompose),
            ),
            returnValueForMissingStub: _FakeClientAicompose_26(
              this,
              Invocation.getter(#aicompose),
            ),
          )
          as _i3.ClientAicompose);

  @override
  set auth(_i3.ClientAuth? value) => super.noSuchMethod(
    Invocation.setter(#auth, value),
    returnValueForMissingStub: null,
  );

  @override
  set account(_i3.ClientAccount? value) => super.noSuchMethod(
    Invocation.setter(#account, value),
    returnValueForMissingStub: null,
  );

  @override
  set users(_i3.ClientUsers? value) => super.noSuchMethod(
    Invocation.setter(#users, value),
    returnValueForMissingStub: null,
  );

  @override
  set contacts(_i3.ClientContacts? value) => super.noSuchMethod(
    Invocation.setter(#contacts, value),
    returnValueForMissingStub: null,
  );

  @override
  set messages(_i3.ClientMessages? value) => super.noSuchMethod(
    Invocation.setter(#messages, value),
    returnValueForMissingStub: null,
  );

  @override
  set updates(_i3.ClientUpdates? value) => super.noSuchMethod(
    Invocation.setter(#updates, value),
    returnValueForMissingStub: null,
  );

  @override
  set photos(_i3.ClientPhotos? value) => super.noSuchMethod(
    Invocation.setter(#photos, value),
    returnValueForMissingStub: null,
  );

  @override
  set upload(_i3.ClientUpload? value) => super.noSuchMethod(
    Invocation.setter(#upload, value),
    returnValueForMissingStub: null,
  );

  @override
  set help(_i3.ClientHelp? value) => super.noSuchMethod(
    Invocation.setter(#help, value),
    returnValueForMissingStub: null,
  );

  @override
  set channels(_i3.ClientChannels? value) => super.noSuchMethod(
    Invocation.setter(#channels, value),
    returnValueForMissingStub: null,
  );

  @override
  set bots(_i3.ClientBots? value) => super.noSuchMethod(
    Invocation.setter(#bots, value),
    returnValueForMissingStub: null,
  );

  @override
  set payments(_i3.ClientPayments? value) => super.noSuchMethod(
    Invocation.setter(#payments, value),
    returnValueForMissingStub: null,
  );

  @override
  set stickers(_i3.ClientStickers? value) => super.noSuchMethod(
    Invocation.setter(#stickers, value),
    returnValueForMissingStub: null,
  );

  @override
  set phone(_i3.ClientPhone? value) => super.noSuchMethod(
    Invocation.setter(#phone, value),
    returnValueForMissingStub: null,
  );

  @override
  set langpack(_i3.ClientLangpack? value) => super.noSuchMethod(
    Invocation.setter(#langpack, value),
    returnValueForMissingStub: null,
  );

  @override
  set folders(_i3.ClientFolders? value) => super.noSuchMethod(
    Invocation.setter(#folders, value),
    returnValueForMissingStub: null,
  );

  @override
  set stats(_i3.ClientStats? value) => super.noSuchMethod(
    Invocation.setter(#stats, value),
    returnValueForMissingStub: null,
  );

  @override
  set chatlists(_i3.ClientChatlists? value) => super.noSuchMethod(
    Invocation.setter(#chatlists, value),
    returnValueForMissingStub: null,
  );

  @override
  set stories(_i3.ClientStories? value) => super.noSuchMethod(
    Invocation.setter(#stories, value),
    returnValueForMissingStub: null,
  );

  @override
  set premium(_i3.ClientPremium? value) => super.noSuchMethod(
    Invocation.setter(#premium, value),
    returnValueForMissingStub: null,
  );

  @override
  set smsjobs(_i3.ClientSmsjobs? value) => super.noSuchMethod(
    Invocation.setter(#smsjobs, value),
    returnValueForMissingStub: null,
  );

  @override
  set fragment(_i3.ClientFragment? value) => super.noSuchMethod(
    Invocation.setter(#fragment, value),
    returnValueForMissingStub: null,
  );

  @override
  set aicompose(_i3.ClientAicompose? value) => super.noSuchMethod(
    Invocation.setter(#aicompose, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i3.Result<_i3.TlObject>> invoke(_i3.TlMethod? method) =>
      (super.noSuchMethod(
            Invocation.method(#invoke, [method]),
            returnValue: _i4.Future<_i3.Result<_i3.TlObject>>.value(
              _FakeResult_27<_i3.TlObject>(
                this,
                Invocation.method(#invoke, [method]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i3.Result<_i3.TlObject>>.value(
                  _FakeResult_27<_i3.TlObject>(
                    this,
                    Invocation.method(#invoke, [method]),
                  ),
                ),
          )
          as _i4.Future<_i3.Result<_i3.TlObject>>);

  @override
  _i4.Future<_i3.Result<T>> invokeAfterMsg<T extends _i3.TlObject>({
    required int? msgId,
    required _i3.TlMethod? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#invokeAfterMsg, [], {
              #msgId: msgId,
              #query: query,
            }),
            returnValue: _i4.Future<_i3.Result<T>>.value(
              _FakeResult_27<T>(
                this,
                Invocation.method(#invokeAfterMsg, [], {
                  #msgId: msgId,
                  #query: query,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.Result<T>>.value(
              _FakeResult_27<T>(
                this,
                Invocation.method(#invokeAfterMsg, [], {
                  #msgId: msgId,
                  #query: query,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.Result<T>>);

  @override
  _i4.Future<_i3.Result<T>> invokeAfterMsgs<T extends _i3.TlObject>({
    required List<int>? msgIds,
    required _i3.TlMethod? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#invokeAfterMsgs, [], {
              #msgIds: msgIds,
              #query: query,
            }),
            returnValue: _i4.Future<_i3.Result<T>>.value(
              _FakeResult_27<T>(
                this,
                Invocation.method(#invokeAfterMsgs, [], {
                  #msgIds: msgIds,
                  #query: query,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.Result<T>>.value(
              _FakeResult_27<T>(
                this,
                Invocation.method(#invokeAfterMsgs, [], {
                  #msgIds: msgIds,
                  #query: query,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.Result<T>>);

  @override
  _i4.Future<_i3.Result<T>> initConnection<T extends _i3.TlObject>({
    required int? apiId,
    required String? deviceModel,
    required String? systemVersion,
    required String? appVersion,
    required String? systemLangCode,
    required String? langPack,
    required String? langCode,
    _i3.InputClientProxyBase? proxy,
    _i3.JSONValueBase? params,
    required _i3.TlMethod? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initConnection, [], {
              #apiId: apiId,
              #deviceModel: deviceModel,
              #systemVersion: systemVersion,
              #appVersion: appVersion,
              #systemLangCode: systemLangCode,
              #langPack: langPack,
              #langCode: langCode,
              #proxy: proxy,
              #params: params,
              #query: query,
            }),
            returnValue: _i4.Future<_i3.Result<T>>.value(
              _FakeResult_27<T>(
                this,
                Invocation.method(#initConnection, [], {
                  #apiId: apiId,
                  #deviceModel: deviceModel,
                  #systemVersion: systemVersion,
                  #appVersion: appVersion,
                  #systemLangCode: systemLangCode,
                  #langPack: langPack,
                  #langCode: langCode,
                  #proxy: proxy,
                  #params: params,
                  #query: query,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.Result<T>>.value(
              _FakeResult_27<T>(
                this,
                Invocation.method(#initConnection, [], {
                  #apiId: apiId,
                  #deviceModel: deviceModel,
                  #systemVersion: systemVersion,
                  #appVersion: appVersion,
                  #systemLangCode: systemLangCode,
                  #langPack: langPack,
                  #langCode: langCode,
                  #proxy: proxy,
                  #params: params,
                  #query: query,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.Result<T>>);

  @override
  _i4.Future<_i3.Result<T>> invokeWithLayer<T extends _i3.TlObject>({
    required int? layer,
    required _i3.TlMethod? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#invokeWithLayer, [], {
              #layer: layer,
              #query: query,
            }),
            returnValue: _i4.Future<_i3.Result<T>>.value(
              _FakeResult_27<T>(
                this,
                Invocation.method(#invokeWithLayer, [], {
                  #layer: layer,
                  #query: query,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.Result<T>>.value(
              _FakeResult_27<T>(
                this,
                Invocation.method(#invokeWithLayer, [], {
                  #layer: layer,
                  #query: query,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.Result<T>>);

  @override
  _i4.Future<_i3.Result<T>> invokeWithoutUpdates<T extends _i3.TlObject>({
    required _i3.TlMethod? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#invokeWithoutUpdates, [], {#query: query}),
            returnValue: _i4.Future<_i3.Result<T>>.value(
              _FakeResult_27<T>(
                this,
                Invocation.method(#invokeWithoutUpdates, [], {#query: query}),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.Result<T>>.value(
              _FakeResult_27<T>(
                this,
                Invocation.method(#invokeWithoutUpdates, [], {#query: query}),
              ),
            ),
          )
          as _i4.Future<_i3.Result<T>>);

  @override
  _i4.Future<_i3.Result<T>> invokeWithMessagesRange<T extends _i3.TlObject>({
    required _i3.MessageRangeBase? range,
    required _i3.TlMethod? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#invokeWithMessagesRange, [], {
              #range: range,
              #query: query,
            }),
            returnValue: _i4.Future<_i3.Result<T>>.value(
              _FakeResult_27<T>(
                this,
                Invocation.method(#invokeWithMessagesRange, [], {
                  #range: range,
                  #query: query,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.Result<T>>.value(
              _FakeResult_27<T>(
                this,
                Invocation.method(#invokeWithMessagesRange, [], {
                  #range: range,
                  #query: query,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.Result<T>>);

  @override
  _i4.Future<_i3.Result<T>> invokeWithTakeout<T extends _i3.TlObject>({
    required int? takeoutId,
    required _i3.TlMethod? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#invokeWithTakeout, [], {
              #takeoutId: takeoutId,
              #query: query,
            }),
            returnValue: _i4.Future<_i3.Result<T>>.value(
              _FakeResult_27<T>(
                this,
                Invocation.method(#invokeWithTakeout, [], {
                  #takeoutId: takeoutId,
                  #query: query,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.Result<T>>.value(
              _FakeResult_27<T>(
                this,
                Invocation.method(#invokeWithTakeout, [], {
                  #takeoutId: takeoutId,
                  #query: query,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.Result<T>>);

  @override
  _i4.Future<_i3.Result<T>>
  invokeWithBusinessConnection<T extends _i3.TlObject>({
    required String? connectionId,
    required _i3.TlMethod? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#invokeWithBusinessConnection, [], {
              #connectionId: connectionId,
              #query: query,
            }),
            returnValue: _i4.Future<_i3.Result<T>>.value(
              _FakeResult_27<T>(
                this,
                Invocation.method(#invokeWithBusinessConnection, [], {
                  #connectionId: connectionId,
                  #query: query,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.Result<T>>.value(
              _FakeResult_27<T>(
                this,
                Invocation.method(#invokeWithBusinessConnection, [], {
                  #connectionId: connectionId,
                  #query: query,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.Result<T>>);

  @override
  _i4.Future<_i3.Result<T>>
  invokeWithGooglePlayIntegrity<T extends _i3.TlObject>({
    required String? nonce,
    required String? token,
    required _i3.TlMethod? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#invokeWithGooglePlayIntegrity, [], {
              #nonce: nonce,
              #token: token,
              #query: query,
            }),
            returnValue: _i4.Future<_i3.Result<T>>.value(
              _FakeResult_27<T>(
                this,
                Invocation.method(#invokeWithGooglePlayIntegrity, [], {
                  #nonce: nonce,
                  #token: token,
                  #query: query,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.Result<T>>.value(
              _FakeResult_27<T>(
                this,
                Invocation.method(#invokeWithGooglePlayIntegrity, [], {
                  #nonce: nonce,
                  #token: token,
                  #query: query,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.Result<T>>);

  @override
  _i4.Future<_i3.Result<T>> invokeWithApnsSecret<T extends _i3.TlObject>({
    required String? nonce,
    required String? secret,
    required _i3.TlMethod? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#invokeWithApnsSecret, [], {
              #nonce: nonce,
              #secret: secret,
              #query: query,
            }),
            returnValue: _i4.Future<_i3.Result<T>>.value(
              _FakeResult_27<T>(
                this,
                Invocation.method(#invokeWithApnsSecret, [], {
                  #nonce: nonce,
                  #secret: secret,
                  #query: query,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.Result<T>>.value(
              _FakeResult_27<T>(
                this,
                Invocation.method(#invokeWithApnsSecret, [], {
                  #nonce: nonce,
                  #secret: secret,
                  #query: query,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.Result<T>>);

  @override
  _i4.Future<_i3.Result<T>> invokeWithReCaptcha<T extends _i3.TlObject>({
    required String? token,
    required _i3.TlMethod? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#invokeWithReCaptcha, [], {
              #token: token,
              #query: query,
            }),
            returnValue: _i4.Future<_i3.Result<T>>.value(
              _FakeResult_27<T>(
                this,
                Invocation.method(#invokeWithReCaptcha, [], {
                  #token: token,
                  #query: query,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.Result<T>>.value(
              _FakeResult_27<T>(
                this,
                Invocation.method(#invokeWithReCaptcha, [], {
                  #token: token,
                  #query: query,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.Result<T>>);
}
